version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node

  node:
    build: ./node
    container_name: node
    volumes:
      - ./node:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && node index.js"
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 5
volumes:
  mysql_data:
